INSERT INTO questions (text, section, difficulty, options, correct_option, weight) VALUES
('Solve the pattern: 2, 4, 8, 16, ?', 'Logical', 'Easy', '["32","24","30","28"]', '32', 1.0),
('Identify the synonym of "abundant"', 'Verbal', 'Easy', '["Scarce","Plentiful","Tiny","Little"]', 'Plentiful', 1.0),
('What is 15 + 27?', 'Numerical', 'Easy', '["42","40","45","44"]', '42', 1.0),
('Which shape comes next in the sequence?', 'Spatial', 'Medium', '["Circle","Square","Triangle","Hexagon"]', 'Triangle', 1.0),
('Do you enjoy coding tasks?', 'Tech interest', 'Easy', '["Yes","No"]', 'Yes', 1.0),
('Do you enjoy leading groups?', 'People/Leadership', 'Easy', '["Yes","No"]', 'Yes', 1.0),
('Find the missing number: 5, 10, 20, 40, ?', 'Logical', 'Medium', '["60","80","70","100"]', '80', 1.0),
('Select the antonym of "brave"', 'Verbal', 'Easy', '["Cowardly","Heroic","Bold","Fearless"]', 'Cowardly', 1.0),
('What is 12 * 7?', 'Numerical', 'Easy', '["84","72","96","90"]', '84', 1.0),
('Which figure completes the pattern?', 'Spatial', 'Medium', '["Star","Circle","Rectangle","Triangle"]', 'Rectangle', 1.0),
('Do you like working with technology?', 'Tech interest', 'Easy', '["Yes","No"]', 'Yes', 1.0),
('Do you prefer teamwork?', 'People/Leadership', 'Easy', '["Yes","No"]', 'Yes', 1.0),
('Solve: 1, 1, 2, 3, 5, ?', 'Logical', 'Medium', '["5","8","7","6"]', '8', 1.0),
('Choose the correct synonym of "elated"', 'Verbal', 'Medium', '["Sad","Joyful","Angry","Confused"]', 'Joyful', 1.0),
('What is 144 ÷ 12?', 'Numerical', 'Easy', '["12","11","13","10"]', '12', 1.0),
('Which 3D shape is this from top view?', 'Spatial', 'Hard', '["Cube","Cylinder","Cone","Sphere"]', 'Cylinder', 1.0),
('Do you enjoy problem-solving?', 'Tech interest', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Do you like mentoring others?', 'People/Leadership', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Find the next in series: 3, 6, 9, 12, ?', 'Logical', 'Easy', '["15","16","18","14"]', '15', 1.0),
('Select the antonym of "optimistic"', 'Verbal', 'Medium', '["Pessimistic","Cheerful","Happy","Bright"]', 'Pessimistic', 1.0),
('What is 50 - 17?', 'Numerical', 'Easy', '["33","35","32","30"]', '33', 1.0),
('Which figure rotates 90 degrees to match?', 'Spatial', 'Medium', '["Square","Triangle","Rectangle","Circle"]', 'Rectangle', 1.0),
('Do you enjoy building websites?', 'Tech interest', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Do you like leading projects?', 'People/Leadership', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Solve the sequence: 10, 20, 40, 80, ?', 'Logical', 'Easy', '["100","120","160","200"]', '160', 1.0),
('Identify the synonym of "rapid"', 'Verbal', 'Easy', '["Fast","Slow","Steady","Lazy"]', 'Fast', 1.0),
('What is 9 * 8?', 'Numerical', 'Easy', '["72","64","81","70"]', '72', 1.0),
('Which pattern completes the figure?', 'Spatial', 'Medium', '["Circle","Square","Triangle","Hexagon"]', 'Hexagon', 1.0),
('Do you enjoy data analysis?', 'Tech interest', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Do you enjoy conflict resolution?', 'People/Leadership', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Find the missing number: 2, 6, 12, 20, ?', 'Logical', 'Medium', '["28","30","32","26"]', '30', 1.0),
('Select the antonym of "generous"', 'Verbal', 'Medium', '["Stingy","Kind","Large","Giving"]', 'Stingy', 1.0),
('What is 81 ÷ 9?', 'Numerical', 'Easy', '["9","8","7","10"]', '9', 1.0),
('Which shape has the most edges?', 'Spatial', 'Medium', '["Cube","Sphere","Cone","Cylinder"]', 'Cube', 1.0),
('Do you enjoy programming in Python?', 'Tech interest', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Do you like organizing teams?', 'People/Leadership', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Next in pattern: 1, 4, 9, 16, ?', 'Logical', 'Medium', '["20","25","30","36"]', '25', 1.0),
('Choose the synonym of "ingenious"', 'Verbal', 'Medium', '["Clever","Dull","Weak","Slow"]', 'Clever', 1.0),
('What is 14 + 29?', 'Numerical', 'Easy', '["43","44","45","42"]', '43', 1.0),
('Which figure is symmetrical?', 'Spatial', 'Medium', '["Circle","Triangle","Arrow","Star"]', 'Circle', 1.0),
('Do you enjoy coding competitions?', 'Tech interest', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Do you like leading teams under pressure?', 'People/Leadership', 'Hard', '["Yes","No"]', 'Yes', 1.0),
('Solve: 5, 10, 15, 20, ?', 'Logical', 'Easy', '["25","30","24","22"]', '25', 1.0),
('Select antonym of "fragile"', 'Verbal', 'Medium', '["Delicate","Sturdy","Weak","Soft"]', 'Sturdy', 1.0),
('What is 36 ÷ 6?', 'Numerical', 'Easy', '["6","5","7","8"]', '6', 1.0),
('Which shape rotates to match the pattern?', 'Spatial', 'Medium', '["Triangle","Square","Rectangle","Circle"]', 'Square', 1.0),
('Do you enjoy AI projects?', 'Tech interest', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Do you enjoy mentoring teams?', 'People/Leadership', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Find next in series: 3, 9, 27, ?', 'Logical', 'Medium', '["54","72","81","9"]', '81', 1.0),
('Choose the synonym of "vivid"', 'Verbal', 'Medium', '["Bright","Dull","Faint","Weak"]', 'Bright', 1.0),
('What is 17 + 23?', 'Numerical', 'Easy', '["40","41","39","42"]', '40', 1.0),
('Which shape has equal sides?', 'Spatial', 'Medium', '["Square","Triangle","Rectangle","Circle"]', 'Square', 1.0),
('Do you enjoy robotics?', 'Tech interest', 'Medium', '["Yes","No"]', 'Yes', 1.0),
('Do you like leading strategic initiatives?', 'People/Leadership', 'Hard', '["Yes","No"]', 'Yes', 1.0);
---50 questions added---
