"""Add is_admin column to users

Revision ID: 05bd9940580b
Revises: 
Create Date: 2025-10-15 13:16:37.109720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05bd9940580b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_assessments_user_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('career_kb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_career_kb_tags'), postgresql_using='gin')

    op.drop_table('career_kb')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_plans_result_id'))

    op.drop_table('plans')
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_responses_assessment_id'))

    op.drop_table('responses')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_results_assessment_id'))

    op.drop_table('results')
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_career_skills'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('idx_careers_track'))
        batch_op.drop_column('sample_roles')
        batch_op.drop_column('track')
        batch_op.drop_column('avg_salary_range')
        batch_op.drop_column('skills')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_questions_section'))
        batch_op.drop_column('section')
        batch_op.drop_column('weight')
        batch_op.drop_column('correct_option')
        batch_op.drop_column('options')
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_users_email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correct_option', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_questions_section'), ['section'], unique=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avg_salary_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('track', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sample_roles', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_careers_track'), ['track'], unique=False)
        batch_op.create_index(batch_op.f('idx_career_skills'), ['skills'], unique=False, postgresql_using='gin')
        batch_op.drop_column('created_at')

    op.create_table('results',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('results_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('primary_track', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('secondary_track', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name='results_assessment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='results_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_results_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selected_option', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('responses_assessment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('responses_question_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('responses_pkey'))
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_responses_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('plans_result_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey'))
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_plans_result_id'), ['result_id'], unique=False)

    op.create_table('career_kb',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('career_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('career_kb_career_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('career_kb_pkey'))
    )
    with op.batch_alter_table('career_kb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_career_kb_tags'), ['tags'], unique=False, postgresql_using='gin')

    op.create_table('assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('assessments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessments_pkey'))
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_assessments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
