"""Rebuild after cleanup

Revision ID: 302e711a9a02
Revises: 
Create Date: 2025-10-28 12:25:11.100178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '302e711a9a02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=255), nullable=True))
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
        batch_op.drop_column('difficulty')
        batch_op.drop_column('correct_option')

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_careers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('scores',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('results_assessment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'assessments', ['assessment_id'], ['id'])
        batch_op.drop_column('secondary_track')
        batch_op.drop_column('primary_track')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_track', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('secondary_track', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('results_assessment_id_fkey'), 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('recommended_careers')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_option', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('correct_answer')

    # ### end Alembic commands ###
