"""Add is_admin

Revision ID: 56e5490bc414
Revises: 6c2b66ad3f57
Create Date: 2025-11-04 16:28:58.187486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56e5490bc414'
down_revision: Union[str, Sequence[str], None] = '6c2b66ad3f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    op.drop_index(op.f('idx_plans_result_id'), table_name='plans')
    op.drop_table('plans')
    op.alter_column('assessments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_assessments_user_id'), table_name='assessments')
    op.drop_constraint(op.f('assessments_user_id_fkey'), 'assessments', type_='foreignkey')
    op.create_foreign_key(None, 'assessments', 'users', ['user_id'], ['id'])
    op.alter_column('career_kb', 'career_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('career_kb', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('career_kb', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('career_kb', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_career_kb_tags'), table_name='career_kb', postgresql_using='gin')
    op.drop_index(op.f('idx_career_skills'), table_name='careers', postgresql_using='gin')
    op.drop_index(op.f('idx_careers_track'), table_name='careers')
    op.add_column('questions', sa.Column('correct_answer', sa.String(length=255), nullable=True))
    op.alter_column('questions', 'section',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('idx_questions_section'), table_name='questions')
    op.drop_column('questions', 'correct_option')
    op.add_column('responses', sa.Column('answer', sa.String(length=255), nullable=True))
    op.add_column('responses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('responses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('idx_responses_assessment_id'), table_name='responses')
    op.drop_constraint(op.f('responses_question_id_fkey'), 'responses', type_='foreignkey')
    op.drop_constraint(op.f('responses_assessment_id_fkey'), 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'responses', 'assessments', ['assessment_id'], ['id'])
    op.create_foreign_key(None, 'responses', 'questions', ['question_id'], ['id'])
    op.drop_column('responses', 'selected_option')
    op.drop_column('responses', 'score')
    op.add_column('results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('results', 'scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_results_assessment_id'), table_name='results')
    op.create_foreign_key(None, 'results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.create_index(op.f('idx_results_assessment_id'), 'results', ['assessment_id'], unique=False)
    op.alter_column('results', 'scores',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('results', 'user_id')
    op.add_column('responses', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('selected_option', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key(op.f('responses_assessment_id_fkey'), 'responses', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('responses_question_id_fkey'), 'responses', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_responses_assessment_id'), 'responses', ['assessment_id'], unique=False)
    op.drop_column('responses', 'created_at')
    op.drop_column('responses', 'user_id')
    op.drop_column('responses', 'answer')
    op.add_column('questions', sa.Column('correct_option', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_questions_section'), 'questions', ['section'], unique=False)
    op.alter_column('questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('questions', 'section',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('questions', 'correct_answer')
    op.create_index(op.f('idx_careers_track'), 'careers', ['track'], unique=False)
    op.create_index(op.f('idx_career_skills'), 'careers', ['skills'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_career_kb_tags'), 'career_kb', ['tags'], unique=False, postgresql_using='gin')
    op.alter_column('career_kb', 'tags',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('career_kb', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('career_kb', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('career_kb', 'career_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.create_foreign_key(op.f('assessments_user_id_fkey'), 'assessments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.alter_column('assessments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('result_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name=op.f('plans_result_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('plans_pkey'))
    )
    op.create_index(op.f('idx_plans_result_id'), 'plans', ['result_id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
