"""Add primary_track, secondary_track, and scores_json to results

Revision ID: 74df521bc6a0
Revises: 302e711a9a02
Create Date: 2025-10-29 13:29:32.243192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74df521bc6a0'
down_revision = '302e711a9a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_track', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('secondary_track', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('scores_json', sa.JSON(), nullable=True))
        batch_op.alter_column('assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('recommended_careers')
        batch_op.drop_column('scores')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recommended_careers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('scores_json')
        batch_op.drop_column('secondary_track')
        batch_op.drop_column('primary_track')

    # ### end Alembic commands ###
