"""Add answer column to responses

Revision ID: 9eca954e707a
Revises: 74df521bc6a0
Create Date: 2025-10-29 13:59:08.843548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eca954e707a'
down_revision = '74df521bc6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('responses_question_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('responses_assessment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])
        batch_op.create_foreign_key(None, 'assessments', ['assessment_id'], ['id'])
        batch_op.drop_column('selected_option')
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('selected_option', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('responses_assessment_id_fkey'), 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('responses_question_id_fkey'), 'questions', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
